### ISSUE TITLE
Question: interested in exposing the builder?

### ISSUE THREAD

**Issue by fawix** [seanmonstar/pretty-env-logger#10]
@seanmonstar  I just created a fork of your logger to expose the env_logger::Builder - I like the formatting but was needing more control over the logger... I also added some more examples.

If you are interested in merging the changes I can send you a pull request for review.

**Comment by seanmonstar** [comment]
Eh, sure! I just made this to be a pretty and easy logger to use when debugging examples in libs I build, but I don't mind if the builder is exposed.

**Comment by fawix** [comment]
Cool!! It's a nice lib! I just send you a pull request, let me know if I should modify anything.
