### ISSUE TITLE
0.2.1 seems to require ansi_term 0.9

### ISSUE THREAD

**Issue by ignatenkobrain** [seanmonstar/pretty-env-logger#12]
Also there is no tag in repository...

**Comment by seanmonstar** [comment]
Yes it does, because 0.10 doesn't work on Windows MSVC. Is there a problem with an internal dependency needing an earlier version?

**Comment by ignatenkobrain** [comment]
@seanmonstar we are trying very hard to avoid packaging multiple versions of crate and so far pretty-env-logger is the only one depending on 0.9 (while perfectly compiles with 0.10), so probably you can make windows-specific dependency on 0.9 while letting rest of the world using 0.10?

**Comment by seanmonstar** [comment]
That seems reasonable!

**Comment by ignatenkobrain** [comment]
Or, better, to fix ansi_term :D

**Comment by seanmonstar** [comment]
Oh yea, definitely that is preferred. Several have tried, seems the author may be MIA: https://github.com/ogham/rust-ansi-term/issues/31

Or perhaps, the dependency should swap from ansi_term to the crate the ripgrep uses. It also better detects if printing to a TTY or if being redirected to a file.

**Comment by seanmonstar** [comment]
OK, I've published v0.2.2 that uses ansi_term 0.10 on all except for windows + x86, which uses 0.9. Also added Travis and AppVeyor CI to ensure they both work.
