### ISSUE TITLE
Changing log level at runtime

### ISSUE THREAD

**Issue by bestouff** [seanmonstar/pretty-env-logger#27]
I'm using `pretty-env-logger` (through `quicli`) for a long-lived daemon, and I would need to dynamically change its log level at runtime (my daemon sends logs via network, and something "in the cloud" may ask it to log more or less).  
How is it possible to do that ? Or if not possible currently, would it be possible as a feature ?

**Comment by seanmonstar** [comment]
I don't believe that is possible to do. The goal of this library is to be very simple, but prettier output than the original `env_logger`. You could look at some of the more complex loggers to see if they have this feature (like fern, or log4rs, or others).

**Comment by bestouff** [comment]
Unfortunately I think I'm stuck with it because of quicli.

**Comment by WhyNotHugo** [comment]
> The goal of this library is to be very simple

Maybe a bit **too** simple. I'm creating re-distributable binaries, and I can't set the default logging to any value.

Assuming my target audience has no idea how to set an environment variable, is it possible to change the log level at all?

**Comment by seanmonstar** [comment]
This feature is out of scope of the library. There *are* more complex loggers that one can configure that sort of thing.
