### ISSUE TITLE
Is this project being maintained ?

### ISSUE THREAD

**Issue by patrickelectric** [seanmonstar/pretty-env-logger#44]
It appears that there are a bunch of staled issues and PRs, if it's not maintained anymore, the repository should be archived or transferred to someone, avoiding unnecessary creation of PRs and issues.

**Comment by seanmonstar** [comment]
I'd say it's passively maintained. I believe the crate does probably everything that *I* think it needs to do. If there's bugs, or new versions needed, they go out.
