### ISSUE TITLE
Please make a new release and publish to crates.io

### ISSUE THREAD

**Issue by nibon7** [seanmonstar/pretty-env-logger#52]
Currently, `env-logger` has been updated to 0.9.0, maybe it's time to release a new version. :)

**Comment by ruffsl** [comment]
Would it be possible to automate this via an github action? Say when the version is bumped on the default branch?

**Comment by epage** [comment]
env_logger 0.10.0 was just released that resolved a soundness issue by switching from `atty` to `is-terminal`.

Please release a new version so cargo and other tools can remove their dependency on `atty`.

**Comment by larsnaesbye** [comment]
Seconding the need for a new release on crates.io. @seanmonstar ?

**Comment by seanmonstar** [comment]
Just published 0.5.0, depending on env-logger 0.10.
